#ifndef LISTENINGTO_GLOBAL_H
#define LISTENINGTO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LISTENINGTO_LIBRARY)
#  define LISTENINGTOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LISTENINGTOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTENINGTO_GLOBAL_H
